#!/usr/bin/env bash
# Generated by nexus-app v0.13.0-dev (abf88069)
# Post-init script for Nexus Dev Full Stack workspace
# This runs after the main devbox init hook

echo "welcome to our nexus-app lokal devbox workspace v0.1.0"
echo ""
echo "  Team:    ${C_DBX_META_TEAM:-unknown}"
echo "  Project: ${C_DBX_META_PROJECT_ID:-unknown}"
echo "  Env:     ${C_DBX_META_PROJECT_ENV:-unknown}"
echo ""
